
package com.mx.pmx.pmi.sad.generadorDocx.integrador.serviceImpl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Sun Nov 22 00:31:17 CST 2015
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "DfException", namespace = "http://common.fc.documentum.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DfException", namespace = "http://common.fc.documentum.com/", propOrder = {"arguments", "count", "errorCode", "message", "messageId", "nextException", "properties", "stackTraceAsString", "tailException", "threadInfo"})

public class DfExceptionBean {

    private [Ljava.lang.Object; arguments;
    private int count;
    private int errorCode;
    private java.lang.String message;
    private java.lang.String messageId;
    private com.documentum.fc.common.IDfException nextException;
    private com.documentum.fc.common.IDfProperties properties;
    private java.lang.String stackTraceAsString;
    private com.documentum.fc.common.IDfException tailException;
    private java.lang.String threadInfo;

    public [Ljava.lang.Object; getArguments() {
        return this.arguments;
    }

    public void setArguments([Ljava.lang.Object; newArguments)  {
        this.arguments = newArguments;
    }

    public int getCount() {
        return this.count;
    }

    public void setCount(int newCount)  {
        this.count = newCount;
    }

    public int getErrorCode() {
        return this.errorCode;
    }

    public void setErrorCode(int newErrorCode)  {
        this.errorCode = newErrorCode;
    }

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

    public java.lang.String getMessageId() {
        return this.messageId;
    }

    public void setMessageId(java.lang.String newMessageId)  {
        this.messageId = newMessageId;
    }

    public com.documentum.fc.common.IDfException getNextException() {
        return this.nextException;
    }

    public void setNextException(com.documentum.fc.common.IDfException newNextException)  {
        this.nextException = newNextException;
    }

    public com.documentum.fc.common.IDfProperties getProperties() {
        return this.properties;
    }

    public void setProperties(com.documentum.fc.common.IDfProperties newProperties)  {
        this.properties = newProperties;
    }

    public java.lang.String getStackTraceAsString() {
        return this.stackTraceAsString;
    }

    public void setStackTraceAsString(java.lang.String newStackTraceAsString)  {
        this.stackTraceAsString = newStackTraceAsString;
    }

    public com.documentum.fc.common.IDfException getTailException() {
        return this.tailException;
    }

    public void setTailException(com.documentum.fc.common.IDfException newTailException)  {
        this.tailException = newTailException;
    }

    public java.lang.String getThreadInfo() {
        return this.threadInfo;
    }

    public void setThreadInfo(java.lang.String newThreadInfo)  {
        this.threadInfo = newThreadInfo;
    }

}

