
package com.mx.pmx.pmi.sad.generadorDocx.integrador.serviceImpl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Sun Nov 22 00:31:15 CST 2015
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "generaChecklistDemoras", namespace = "http://serviceImpl.integrador.generadorDocx.sad.pmi.pmx.mx.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "generaChecklistDemoras", namespace = "http://serviceImpl.integrador.generadorDocx.sad.pmi.pmx.mx.com/", propOrder = {"arg0", "arg1", "arg2"})

public class GeneraChecklistDemoras {

    @XmlElement(name = "arg0")
    private com.mx.pmx.pmi.sad.generadorDocx.integrador.bean.ChecklistDemorasBean arg0;
    @XmlElement(name = "arg1")
    private com.mx.pmx.pmi.sad.generadorDocx.integrador.bean.GeneradorBean arg1;
    @XmlElement(name = "arg2")
    private java.util.Map<java.lang.String, java.lang.String> arg2;

    public com.mx.pmx.pmi.sad.generadorDocx.integrador.bean.ChecklistDemorasBean getArg0() {
        return this.arg0;
    }

    public void setArg0(com.mx.pmx.pmi.sad.generadorDocx.integrador.bean.ChecklistDemorasBean newArg0)  {
        this.arg0 = newArg0;
    }

    public com.mx.pmx.pmi.sad.generadorDocx.integrador.bean.GeneradorBean getArg1() {
        return this.arg1;
    }

    public void setArg1(com.mx.pmx.pmi.sad.generadorDocx.integrador.bean.GeneradorBean newArg1)  {
        this.arg1 = newArg1;
    }

    public java.util.Map<java.lang.String, java.lang.String> getArg2() {
        return this.arg2;
    }

    public void setArg2(java.util.Map<java.lang.String, java.lang.String> newArg2)  {
        this.arg2 = newArg2;
    }

}

